name: Build & Release APK

on:
  push:
    tags:
      - 'v*' # Memicu workflow hanya jika ada tag yang di-push (contoh: v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Java (Wajib untuk Android)
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Akan menggunakan versi stabil terbaru
          channel: 'stable'

      # 4. Secrets
      - name: Create env.dart from Secrets
        run: |
          mkdir -p lib/config
          echo "const String baseUrl = '${{ secrets.BASE_URL }}';" > lib/config/env.dart

      # 5. Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 6. Build APK Release
      - name: Build APK
        run: flutter build apk --release

      # 7. Buat Release di GitHub dan Upload APK
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "APK otomatis untuk versi ${{ github.ref_name }}"   